spring:
  jpa:
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  thymeleaf:
    cache: true

#liquibase:
#  change-log:
#    classpath:/changelog/db.changelog-master.xml
